apiVersion: v1
kind: Service

metadata:
    name: client-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: web
    #tells other objects to get into the client pods, a port 3000 is needed
    ports:
        - port: 3000
          targetPort: 3000
        

