apiVersion: v1
kind: Service

metadata:
    name: postgres-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: postgres
    #tells other objects to get into the client pods, a port 5000 is needed
    ports:
        - port: 5432
          targetPort: 5432

